### PR TITLE
Combine decagon and ultrasonic UARTs

### PR DESCRIPTION
**Pull request by imondrag**
Combining these two UARTs (with the help of the currently used MUX) should allow us to use the extra UART for debugging. This is also a foundation for remotely assigning pins.

### CODE REVIEW

**Comment by mdbartos** [comment]
The error you're getting is fixed in #37 

The decagon sensor is reporting 9999's though.

**Comment by mdbartos** [comment]
Edit: Nevermind. The error you're getting is because the decagon is reporting 9999. It just hits another error afterwards that was fixed in #37

**Comment by imondrag** [comment]
I can think of two problems that may be causing this.
- The clock division may not be accurate enough for the required baud rate of 1200 for the decagon sensor
- And/Or The combined interrupt service might not be set up properly

**Comment by mdbartos** [comment]
We might want to give the UART full duplex so that it can send commands to the attached device. This is needed for MODBUS sensors (like the Senix Toughsonic).

**Comment by mdbartos** [comment]
Just checking: can you get a baud rate > 9600 with this approach?

**Comment by mdbartos** [comment]
Ah, I see. It looks like you used the following equation for the baud rate:

`baud = master_clock_freq // (8 * divisor)`

So our maximum baud rate is 3,000,000?

Probably could put this equation in one of the doxygen strings.

**Comment by imondrag** [comment]
Yeah, the UART needs a clock frequency that's 8x the target baud rate. So a baud rate of 9600 requires a clock of 76800 Hz.

You can use the equation you derived to get the divisor easily. I'm working on cleaning up the working code to allow for arbitrary baud rates at run time.

**Comment by mdbartos** [comment]
Let me know when you're ready to merge.

**Pull request merged**
